---
title: "Milwaukee_Consulting"
author: "Aldrich Paras"
date: "9/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#upload data
load("consulting_data.RData")
View(final)
```



```{r}
#exploratory data analysis
par(mfrow = c(2,2))
hist(final$KITCHEN_CT)
hist(final$FULL_BATH_CT)
hist(final$HALF_BATH_CT)
plot(final$FINISHED_AREA,final$SALE_PRICE)
  
```


```{r}
# change character variables to factor


final$BLD_TYPE <- as.factor(final$BLD_TYPE)
levels(final$BLD_TYPE)
final$APPRAISER <- as.factor(final$APPRAISER)
levels(final$APPRAISER)
final$NBHD <- as.factor(final$NBHD)
levels(final$NBHD)
final$QUAL <- as.factor(final$QUAL)
final$COND <- as.factor(final$COND)
final$KITCHEN_RATING <- as.factor(final$KITCHEN_RATING)
final$FULL_BATH_RATING <- as.factor(final$FULL_BATH_RATING)
final$HALF_BATH_RATING <- as.factor(final$HALF_BATH_RATING)

```

```{r}
#subsetting dataframe based on appealed or not

# Properties appealed either 2019 OR 2020 OR 2021
appealed_Full <- final[which(final$APPEALED19 == TRUE | final$APPEALED20 == TRUE | final$APPEALED21 == TRUE),]

# Properties appealed in 2021 - 517 observations
appealed_2021 <- final[which(final$APPEALED21 == TRUE),]



# Properties from any year that have a sale price
house_Sold <- subset(final, (!is.na(final$SALE_PRICE)))

```

```{r}
# Linear regression on houses with sale price and every predictor
model_Full <- lm(SALE_PRICE ~ BLD_TYPE + APPRAISER + NBHD + QUAL + COND + KITCHEN_CT + KITCHEN_RATING + FULL_BATH_CT + FULL_BATH_RATING + HALF_BATH_CT + HALF_BATH_RATING + YEAR_BUILT + FINISHED_AREA + LAND_SF +  SALE_DATE, data  = house_Sold )
summary(model_Full)
```

